### ISSUE TITLE
Completed task is shown briefly after refresh

### ISSUE THREAD

**Issue by ruudkok** [Brainsupporter/Issues#10] opened 2024-12-04 10:03 UTC
When I press F5 or do a page refresh, an already completed task is briefly shown.

See the below screenshot, where already completed task **2** is being shown.
![afbeelding](https://github.com/user-attachments/assets/06db47a7-01ed-43e6-9f65-b19d9a24f151)

After a second, task no 2 disappears again.
In this case, it's always task no 2 that appears and quickly disappears, so the completed task that's briefly shown does not seem random.

**Comment by raseesink** [comment] 2024-12-04 11:20
So that happens everytime, right after the sync has finished? (icon on the right upper corner)?
If this is firefox, does it also happen in chrome? And what happens in a private window in the same browser?

**Comment by ruudkok** [comment] 2024-12-04 12:03
Browser: Firefox 134.0b4.

Happens every time, right after sync has finished. (little icon upper right corner disappears and then also the task disappears)
Same problem in private window in Firefox.

Also happens in Edge 131.0.2903.70

**Comment by raseesink** [comment] 2024-12-04 20:30
The problem is fixed by fixing a issue in the ordering of events. Will be released today, let us know if that didn't work.

**Closed as completed** 2024-12-04 20:32 UTC
